### ISSUE TITLE
window.electron: Unresolved variable electron

### ISSUE THREAD

**Issue by joyexpr** [alex8088/quick-start#1]
### Describe the bug

yarn create @quick-start/electron，选择vue typescript，在renderer中的vue组件中（如Versions.vue），window.electron 无法识别，在env.d.ts中添加以下声明也无效：

import { ElectronAPI } from '@electron-toolkit/preload'
declare global {
  interface Window {
    electron: ElectronAPI
    api: unknown
  }
}

![WX20220907-144258@2x](https://user-images.githubusercontent.com/4078122/188807567-21bef2b3-78a5-406f-86e9-0298213356fa.png)

### Used Scaffolding

create-electron

### Used Package Manager

yarn

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
有vue的IDE插件吗 TypeScript Vue Plugin (Volar)，我在vscode下没有问题

**Comment by alex8088** [comment]
![2](https://user-images.githubusercontent.com/25053004/188811331-fbe38666-1400-4334-a65e-7804af021946.png)
在vscode中是可以知道 tsconfig是否对文件生效的，如上图，不了解你的IDE

**Comment by joyexpr** [comment]
webstorm没有volar插件，有安装官方的vue.js插件

试了下把tsconfig.web.json的内容拷到tsconfig.json就正常了

**Comment by alex8088** [comment]
> webstorm没有volar插件，有安装官方的vue.js插件
> 
> 试了下把tsconfig.web.json的内容拷到tsconfig.json就正常了

这大致和IDE相关，webstorm不知道是用代码安装ts还是自带， references 要求 ts 3.0以上

**Comment by joyexpr** [comment]
显示是用的项目自带的依赖typescript 4.8.2，目前使用没问题，我先继续留意

**Comment by joyexpr** [comment]
> > webstorm没有volar插件，有安装官方的vue.js插件
> > 试了下把tsconfig.web.json的内容拷到tsconfig.json就正常了
> 
> 这大致和IDE相关，webstorm不知道是用代码安装ts还是自带， references 要求 ts 3.0以上

可能是跟IDE有关，我的IDE版本如下：macOS 10.15.7，WebStorm 2021.3，Vue.js插件版本：213.5744.224，typescript: 4.8.3

目前我尝试出来的尽量不修改模板的改动如下：

删除tsconfig.json中的 files:[] 这行，删除后 webstorm就可以resolve到window.electron了，不知道vscode删除这行会不会有影响。

---- 补充
删除files:[]后，执行typecheck(tsc --noEmit)会报错，把typecheck修改为另一个issue您回复的：
"typecheck": "tsc --noEmit -p tsconfig.node.json --composite false",  
便正常了

**Comment by alex8088** [comment]
删除 `files:[]`也是可以的，

typecheck这部分都要改，.vue 后缀也是
