### ISSUE TITLE
New project shows errors on many imports in VSCode

### ISSUE THREAD

**Issue by ryantrem** [alex8088/quick-start#11]
### Describe the bug

After creating a new project via `npm create @quick-start/electron electron-test -- --template react-ts`, I see errors on many imports in various `.ts` and `.tsx` files, as well as with the `extends` property in the tsconfig files. Adding `"allowSyntheticDefaultImports": true,` to both `tsconfig.node.json` and `tsconfig.web.json` seems to resolve the issue, but if that is the correct configuration then I would expect it to be part of the default template.

### Used Scaffolding

create-electron

### Used Package Manager

npm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
it works in my vscode.
