### ISSUE TITLE
multiple windows , secondary renderer process requiring npm run build

### ISSUE THREAD

**Issue by stuartambient** [alex8088/quick-start#15]
### Describe the bug

I have a multiple windows app.  I'm finding for the second renderer process, any changes I make in the code requires me to run npm run build first.  Something I'm doing wrong ?  Generally with the first renderer, it may have required me to restart (npm run dev) but not specifically use npm run build before.  

```
/* ELECTRON VITE CONFIG */
import { resolve } from 'path';
import { defineConfig, externalizeDepsPlugin } from 'electron-vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()]
  },
  preload: {
    plugins: [externalizeDepsPlugin()],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/preload/index.js'),
          child: resolve(__dirname, 'src/preload/child.js')
        }
      }
    }
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src')
      }
    },
    build: {
      rollupOptions: {
        input: {
          main: resolve(__dirname, 'src/renderer/index.html'),
          child: resolve(__dirname, 'src/renderer/child.html')
        }
      }
    },
    plugins: [react()]
  }
});```

```
/* RELEVANT PACKAGE.JSON */
scripts": {
    "format": "prettier --write .",
    "lint": "eslint . --ext .js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix",
    "start": "electron-vite preview",
    "dev": "electron-vite dev --watch",
    "build": "electron-vite build",
    "postinstall": "electron-builder install-app-deps",
    "build:win": "npm run build && electron-builder --win --config",
    "build:mac": "npm run build && electron-builder --mac --config",
    "build:linux": "npm run build && electron-builder --linux --config"
  },```

### Used Scaffolding

create-electron

### Used Package Manager

npm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
I don't not quite understand your problem. About hmr?
https://evite.netlify.app/guide/hmr-in-renderer.html

**Comment by stuartambient** [comment]
> I don't not quite understand your problem. About hmr? https://evite.netlify.app/guide/hmr-in-renderer.html

Yes, HMR, I  wasn't completely sure but after I made the changes (from the link) the HMR seemed to work but it gave me errors in the renderer and the browserWindow itself where the menu disappeared.  I'm not sure what is going on.

//Main window
```function createWindow() {
  mainWindow = new BrowserWindow({
    width: 660,
    height: 600,
    frame: false,
    transparent: true,
    resizable: false,
    show: false,
    ...(process.platform === 'linux'
      ? {
          icon: path.join(__dirname, '../../build/icon.png')
        }
      : {}),
    webPreferences: {
      preload: path.join(__dirname, '../preload/index.js'),
      sandbox: false,
      webSecurity: false,
      nodeIntegration: true
    }
......
 if (is.dev && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(`${process.env['ELECTRON_RENDERER_URL']}/index.html`);
  } else {
    mainWindow.loadFile(`path.join(__dirname, '../renderer/index.html`);
  }
......

Then when I create the child window in another handler - 
``` // Child window
pcMain.handle('show-child', (event, args) => {
  const newWin = new BrowserWindow({
    width: 375,
    height: 550,
    .......

    webPreferences: {
      preload: path.join(__dirname, '../preload/child.js'),
    ....
    }
  });

   if (!app.isPackaged && process.env['ELECTRON_RENDERER_URL']) {
    mainWindow.loadURL(`${process.env['ELECTRON_RENDERER_URL']}/child.html`);
  } else {
    mainWindow.loadFile(path.join(__dirname, '../renderer/child.html'));```

  });```

In the child preload I have 1 listener , if I use the above throws the error - 

```import { contextBridge, ipcRenderer } from 'electron';
import { electronAPI } from '@electron-toolkit/preload';

// Custom APIs for renderer
const childapi = {
  onSendToChild: (cb) => ipcRenderer.once('send-to-child', (event, ...args) => cb(args))
};

if (process.contextIsolated) {
  try {
    contextBridge.exposeInMainWorld('electron', electronAPI);
    contextBridge.exposeInMainWorld('childapi', childapi);
  } catch (error) {
    console.error(error);
  }
} else {
  window.electron = electronAPI;
  window.api = api;
}
```

**Comment by stuartambient** [comment]
> I don't not quite understand your problem. About hmr? https://evite.netlify.app/guide/hmr-in-renderer.html

Was the hmr, got it now.
