### ISSUE TITLE
/build directory conflict with node-gyp

### ISSUE THREAD

**Issue by peter-pakanun** [alex8088/quick-start#18]
### Describe the bug

While developing native addon that is also a part of the electron application, `node-gyp rebuild` will remove all build resources inside `/build` directory, which is causing build process to fail because `build\notarize.js` module was missing.

Most of the time, `/build` directory is a directory associated with build-time temporary files, it is better to choose another name for the buildResources directory.

### Used Scaffolding

create-electron

### Used Package Manager

pnpm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
you  can configure it in `electron-builder.yml`:

```yaml
directories:
  buildResources: build
```
