### ISSUE TITLE
Vanillajs template missing vite config

### ISSUE THREAD

**Issue by alexeski** [alex8088/quick-start#19]
### Describe the bug

I've just discovered vite, not very familiar yet, but when I compare the vanilla js sample with all other samples (incl. Vanilla ts), it seems to be missing vite configs.
 Is this intended or a "bug" (i.e. vite really not enabled in the vanilla js template)?

### Used Scaffolding

create-electron

### Used Package Manager

npm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Support now
