### ISSUE TITLE
tsc --noEmit无效

### ISSUE THREAD

**Issue by joyexpr** [alex8088/quick-start#2]
### Describe the bug

yarn create @quick-start/electron，选择vue typescript，typescript版本为：4.8.3（4.7.4也试过）

ts文件（如main/index.ts）中随便写一句非法语句，如a = b，执行npm run typecheck，无法检出该错误

是否是tsconfig配置有些问题？我随便拷了一个服务端项目的tsconfig配置执行tsc可以检出错误

### Used Scaffolding

create-electron

### Used Package Manager

yarn

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
我看看

**Comment by alex8088** [comment]
@joyexpr  谢谢你的反馈，确实有问题

可以将typecheck改为

`tsc --noEmit -p tsconfig.node.json --composite false`

后面脚手架还会加入vue-tsc对vue构建的渲染进程代码进行类型检查
