### ISSUE TITLE
Question: type of Window.api

### ISSUE THREAD

**Issue by mdruuu** [alex8088/quick-start#20]
### Clear and concise description of the problem

Hi, 

I am wondering why the api type is set as 'unknown' vs electron being ElectronAPI?

import { ElectronAPI } from '@electron-toolkit/preload'

declare global {
  interface Window {
    electron: ElectronAPI
    api: unknown
  }
}

Thank you

### Used Scaffolding

create-electron

### Suggested solution

n/a

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
You can define specific types according to your own module.
