### ISSUE TITLE
Electron BrowserWindow can not be setted Icon on release

### ISSUE THREAD

**Issue by elevenwin** [alex8088/quick-start#3]
### Describe the bug

Scaffold：npm create @quick-start/electron

In debug mode, it is worked that icon was setted to the BrowserWindow 's property.
After released, it is not worked.
It's not allowed to add picture to the window, like Electron's Tray.(it was required a parameter as the icon path).

### Used Scaffolding

create-electron

### Used Package Manager

npm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@elevenwin , you can create a folder in root. e.g.

```
├──src
├──resources   # as public dir
│  └──icon.icon
└──package.json
```

**Comment by elevenwin** [comment]
It works,Thank you!!!
