### ISSUE TITLE
项目打包后白屏

### ISSUE THREAD

**Issue by DongAndDi** [alex8088/quick-start#35]
### Describe the bug

使用的是react-ts项目，项目正常运行没问题。但在windows平台打包后运行exe，应用白屏，无任何渲染进程的展示。

### Used Scaffolding

create-electron

### Used Package Manager

yarn

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/troubleshooting#vue-router-%E6%88%96-react-router-dom-%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E6%AD%A3%E5%B8%B8-%E4%BD%86%E5%9C%A8%E6%9E%84%E5%BB%BA%E5%90%8E%E6%97%A0%E6%95%88

**Comment by DongAndDi** [comment]
> https://cn.electron-vite.org/guide/troubleshooting#vue-router-%E6%88%96-react-router-dom-%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E6%AD%A3%E5%B8%B8-%E4%BD%86%E5%9C%A8%E6%9E%84%E5%BB%BA%E5%90%8E%E6%97%A0%E6%95%88

感谢~
