### ISSUE TITLE
如何在主进程中使用环境变量？

### ISSUE THREAD

**Issue by ArcherTrister** [alex8088/quick-start#4]
### Describe the bug

![image](https://user-images.githubusercontent.com/35516482/204750029-cf7ca80a-1ccb-4d5e-a14f-01e074bbccff.png)

![image](https://user-images.githubusercontent.com/35516482/204750080-7a0287cf-d982-4843-871b-53d749031c31.png)

![image](https://user-images.githubusercontent.com/35516482/204750191-92f8374d-0faa-4aa3-b8f9-16d91c81f4ca.png)

按照文档进行配置，在主进程打印值为 undefined.

### Used Scaffolding

create-electron

### Used Package Manager

yarn

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
先确认修复ts警告，你的写法不正确，可参考 https://github.com/alex8088/electron-vite-bytecode-example

此外可关注 https://github.com/alex8088/electron-vite

**Comment by ArcherTrister** [comment]
![image](https://user-images.githubusercontent.com/35516482/204757817-1d6eea4d-6ec6-4186-8432-835400616d94.png)

![image](https://user-images.githubusercontent.com/35516482/204757888-8851e60f-95f3-46dc-b3b8-acc578a5e9d3.png)


这个警告应该是我编辑器配置的问题，加上我截图的时候智能感知它还没有反应过来，我把上面的项目克隆下来是一样的报错

**Comment by ArcherTrister** [comment]
![image](https://user-images.githubusercontent.com/35516482/204758636-c018db38-e5a0-4945-80d5-ffc64161bb62.png)

运行也是一样的结果，是否要打包才能使用？

**Comment by alex8088** [comment]
示例的变量是 test mode下的 执行  "test:fixes": "electron-vite preview --mode test"，就可以看到了

**Comment by ArcherTrister** [comment]
抱歉，没看环境变量文件，我的失误，非常感谢，能获取到了，我放在.env下不需要指定mode，第一次没有获取到可能是主进程的env.d.ts拷贝的渲染进程的文件或者刷新不及时报错导致的。
