### ISSUE TITLE
Can you also include clean solid build?

### ISSUE THREAD

**Issue by Tetrax-10** [alex8088/quick-start#5]
### Clear and concise description of the problem

I use [electron-vite/solid/js](https://github.com/alex8088/quick-start/tree/master/packages/create-electron/playground/solid) for my current project i dont use eslint or prettier can you add a clean build with just `electron + vite + solid` ?

or create a blog post on how to build clean bulid `electron-vite` and solid ?

### Used Scaffolding

create-electron

### Suggested solution

create a blog post on how to build clean bulid `electron-vite` and solid ?

### Alternative

add a clean build

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
You only need to remove the relevant files of eslint and pertter in root, and remove the dependencies of `eslint*` and `prettier*`.

**Comment by Tetrax-10** [comment]
thx. Is there any blog post/article on creating our own `electron + vite + solid` using `electron-vite` ?

**Comment by alex8088** [comment]
check out https://evite.netlify.app/

https://github.com/alex8088/electron-vite

**Comment by Tetrax-10** [comment]
also if i do npm install it install electron-builder  version=23.6.0 and says 9 vulnerabilities
![image](https://user-images.githubusercontent.com/75513645/207426672-b49a0d93-dfab-4316-a969-6fb94c39cab6.png)

**Comment by alex8088** [comment]
Please ignore, this is normal

**Comment by Tetrax-10** [comment]
how do i use electron-reload with [electron-vite/solid/js](https://github.com/alex8088/quick-start/tree/master/packages/create-electron/playground/solid)?

**Comment by alex8088** [comment]
Do not need to use electron-reload.  electron-vite support hot-reloading. https://evite.netlify.app/guide/hot-reloading.html

**Comment by Tetrax-10** [comment]
Thanks for clearing my doubt. Sorry for asking basic ques, this gonna be my first electron and solidjs project.

**Comment by alex8088** [comment]
Good job. If you have any other questions, please feel free to submit an issue.

**Comment by Tetrax-10** [comment]
Hi me again, i imported `scss` and its working fine. but i didnt change anything on the `electron.vite.config.js`. should i change anything on config to optimize `scss`

Also vite is appending all the `css` and `scss` files to the head. is that normal or vite should combine all the css and scss to 1 file then append it to head?

**Comment by Tetrax-10** [comment]
Hi am using this boilerplate `npm create @quick-start/electron`
after building and installing it through `.exe` from the dist folder its getting installed in `%localappdata%/programs/my-app/my-app.exe`.
how do i change the install location to `%localappdata%/my-app/my-app.exe`

**Comment by alex8088** [comment]
learn more about [electron-builder](https://www.electron.build/)
