### ISSUE TITLE
脚手架目前创建的项目 vite版本是3.x 

### ISSUE THREAD

**Issue by duansheli** [alex8088/quick-start#6]
### Clear and concise description of the problem

vite 版本已经到4.x 了 

目前创建项目的命令  `npm create @quick-start/electron my-app -- --template vue`
创建后的项目 vite 版本是 3.2.4

### Used Scaffolding

create-electron

### Suggested solution

升级版本

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/quick-start/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/quick-start/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/quick-start#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/quick-start/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
稍后会更新

**Comment by alex8088** [comment]
new ver is out!
