### ISSUE TITLE
Help wanted - how to load an additonal html 

### ISSUE THREAD

**Issue by stuartambient** [alex8088/quick-start#8]
### Help wanted

This is using React in renderer.  
I want to use a child.html like index.html  child.html would have a different mount point for what I call ChildApp.jsx.
How to get this working with the './out/ ?

My child.html is sitting in the same place as my index ./src/renderer but Vite doesn't seem to crawl and find the child.html

### Used Scaffolding

create-electron

**Comment by alex8088** [comment]
the scaffolding tool for electron-vite.  see https://evite.netlify.app/
https://evite.netlify.app/guide/dev.html

**Comment by stuartambient** [comment]
> the scaffolding tool for electron-vite. see https://evite.netlify.app/ https://evite.netlify.app/guide/dev.html

I already have the project.  I've added an additional html file and want to know how it gets rolled into the .out directory since that is the main entry point.

**Comment by alex8088** [comment]
Multiple entry points can be configured in the configuration file. see https://evite.netlify.app/guide/dev.html multiple windows part

**Comment by stuartambient** [comment]
does this section remain then and I add in the rollup options ?

```renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src')
      }
    },```

**Comment by stuartambient** [comment]
Ok, got things working without a glitch!
